# Generated by Django 4.0.1 on 2022-02-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mail_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
