# Generated by Django 4.0.1 on 2022-02-23 22:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_userprofile_mail_time_userprofile_hour_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_mailed',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 23, 22, 59, 2, 903443), null=True),
        ),
    ]
