# Generated by Django 4.0.1 on 2022-02-24 22:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_userprofile_last_mailed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='minute',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mail_time',
            field=models.TimeField(default=datetime.time(22, 23, 52, 913944)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_mailed',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 24, 22, 23, 52, 913967, tzinfo=utc), null=True),
        ),
    ]
